### ISSUE TITLE
feature request:  CORS

### ISSUE THREAD

**Issue by henkstom** [Moonware/cordova-cameraserver#1]
What a great tool. 

I am running into this issue when trying to process a image from the cameraserver.

--- Unable to get image data from canvas because the canvas has been tainted by cross-origin data.

Is it possible to add CORS support to the cameraserver?

**Comment by tarun1793** [comment]
Added CORS. Just update the plugin.

**Comment by w3t** [comment]
Thanks Tarun for contributing!

**Comment by tarun1793** [comment]
You're welcome!

**Comment by tarun1793** [comment]
Please close this issue, @henkstom

**Comment by henkstom** [comment]
thanks
